services:
  db:
    image: postgres:16
    container_name: fosiles_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fosiles_user
      POSTGRES_PASSWORD: fosiles123
      POSTGRES_DB: fosiles_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: